"""empty message

Revision ID: 2340f1fb3e4b
Revises: 26d1f9b4ce93
Create Date: 2023-02-08 13:54:32.177955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2340f1fb3e4b'
down_revision = '26d1f9b4ce93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduler_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('scheduler_id')

    # ### end Alembic commands ###
